---
title: "Navigation_Analysis"
output: html_document
date: "2024-06-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(MuMIn)
library(car)
library(effectsize)
```




```{r}
Coverage <- read.csv('/Volumes/TwoTeras/Graph_Stuff/CSVs/Unique_NodeVisit_Ratios.csv')
# Exclude two participants because they were exposed to Vincent's experiment
Mask_IDs <- Coverage$ParticipantID %in% c(5238, 8695)
Coverage <- Coverage[!Mask_IDs, ]

```




```{r}
library(dplyr)


Coverage <- Coverage %>%
 mutate(Experiment = as.factor(Experiment)) %>%
  mutate(
    Experiment = case_when(
      Experiment == "Exp1" ~ 0.5,
      Experiment == "Exp2" ~ 0.5,
      Experiment == "Control" ~ -0.5,
      TRUE ~ NaN
    )
  )

# Count the number of unique IDs in each experimental group
unique_id_counts <- Coverage %>%
  group_by(Experiment) %>%
  summarise(unique_id_count = n_distinct(ParticipantID))

# Print the result
print(unique_id_counts)

Coverage$Session <- as.factor(Coverage$Session)
contrasts(Coverage$Session ) <- contr.treatment(5)
```

```{r}
# based on variable values
# Filter the rows where Experiment == -0.5
filtered_df <- subset(Coverage, Experiment == "Control")

# Get the unique IDs
unique_ids <- unique(filtered_df$ParticipantID)

print(unique_ids)

```

```{r}
unique_ids <- unique(Coverage$ParticipantID)
unique_ids
```

`



```{r}

Coverage_model <- lmer(IndividualRatio ~ SessionNr*Experiment + (1 | ParticipantID), data = Coverage)
summary(Coverage_model)

# Compute R-squared values (marginal and conditional)
r2_values <- r.squaredGLMM(Coverage_model)
print(r2_values)  # R²m (fixed effects), R²c (fixed + random effects)

# Perform Type II ANOVA to get effect sizes
anova_results <- Anova(Coverage_model, type = "II")
print(anova_results)

# Compute eta-squared (η²) for fixed effects
eta_sq_results <- eta_squared(Coverage_model, partial = TRUE)
print(eta_sq_results)
```


```{r}
# Load necessary libraries


library(MuMIn)
library(pwr)

# Compute R² values for the mixed model
r2_values <- r.squaredGLMM(Coverage_model)

# Extract Marginal R² (variance explained by fixed effects)
r2_marginal <- r2_values[1,1]  # First column is R²m
print(paste("Marginal R² (fixed effects):", r2_marginal))

# Compute Cohen’s f² using the dynamically obtained R²m
f2_value <- r2_marginal / (1 - r2_marginal)
print(paste("Cohen's f²:", f2_value))



# Compute power using the dynamically obtained f² value
power_result <- pwr.f2.test(u = 4, v = 260, f2 = f2_value, sig.level = 0.05, power = NULL)

# Print the estimated power
print(power_result)




```


```{r}

Coverage_model <- lmer(CummulativeRatio ~ Session*Experiment + (1 | ParticipantID), data = Coverage)
summary(Coverage_model)

# Compute R-squared values (marginal and conditional)
r2_values <- r.squaredGLMM(Coverage_model)
print(r2_values)  # R²m (fixed effects), R²c (fixed + random effects)

# Perform Type II ANOVA to get effect sizes
anova_results <- Anova(Coverage_model, type = "II")
print(anova_results)

# Compute eta-squared (η²) for fixed effects
eta_sq_results <- eta_squared(Coverage_model, partial = TRUE)
print(eta_sq_results)

```
```{r}
# Compute R² values for the mixed model
r2_values <- r.squaredGLMM(Coverage_model)

# Extract Marginal R² (variance explained by fixed effects)
r2_marginal <- r2_values[1,1]  # First column is R²m
print(paste("Marginal R² (fixed effects):", r2_marginal))

# Compute Cohen’s f² using the dynamically obtained R²m
f2_value <- r2_marginal / (1 - r2_marginal)
print(paste("Cohen's f²:", f2_value))



# Compute power using the dynamically obtained f² value
power_result <- pwr.f2.test(u = 4, v = 260, f2 = f2_value, sig.level = 0.05, power = NULL)

# Print the estimated power
print(power_result)
```



```{r}
Cummu <- Coverage[Coverage$Session == "5", ]
mean_column1 <- mean(Cummu$CummulativeRatio)
sd_column1 <- sd(Cummu$CummulativeRatio)

# Print the results
print(paste("Mean of CummulativeRatio:", mean_column1))
print(paste("Standard Deviation of CummulativeRatio:", sd_column1))
```



```{r}
Navigation <- read.csv("/Volumes/TwoTeras/Graph_Stuff/CSVs/Total_DecisionCounts.csv", sep =",")
# Exclude two participants because they were exposed to Vincent's experiment
Mask_IDs <- Navigation$ParticipantId %in% c(5238, 8695)
Navigation <- Navigation[!Mask_IDs, ]
unique(Navigation$ParticipantId)
```


```{r}
Navigation <- Navigation %>%
 mutate(Experiment = as.factor(Experiment)) %>%
  mutate(
    Experiment = case_when(
      Experiment == "Exp1" ~ 0.5,
      Experiment == "Exp2" ~ 0.5,
      Experiment == "Control" ~ -0.5,
      TRUE ~ NaN
    )
  )

# Count the number of unique IDs in each experimental group
unique_id_counts <- Navigation %>%
  group_by(Experiment) %>%
  summarise(unique_id_count = n_distinct(ParticipantId))

# Print the result
print(unique_id_counts)

Navigation$Session <- as.factor(Navigation$Session)
contrasts(Navigation$Session ) <- contr.treatment(5)

```

```{r}
# Convert Experiment and Strategy to factors
Navigation$Experiment <- as.factor(Navigation$Experiment)
Navigation$Strategy <- as.factor(Navigation$Strategy)
Navigation$Session <- as.factor(Navigation$Session)


# Apply effect coding: -0.5 and 0.5
contrasts(Navigation$Experiment) <- matrix(c(-0.5, 0.5), ncol = 1)
contrasts(Navigation$Strategy) <- matrix(c(-0.5, 0.5), ncol = 1)
contrasts(Navigation$Session ) <- contr.treatment(5)

```

```{r}
Decisions <- lmer(StrategyCount ~ Session * Strategy + Experiment + (1 | ParticipantId), data = Navigation)
summary(Decisions)

# Compute R-squared values (marginal and conditional)
r2_values <- r.squaredGLMM(Decisions)
print(r2_values)  # R²m (fixed effects), R²c (fixed + random effects)

# Perform Type II ANOVA to get effect sizes
anova_results <- Anova(Decisions, type = "II")
print(anova_results)

# Compute eta-squared (η²) for fixed effects
eta_sq_results <- eta_squared(Decisions, partial = TRUE)
print(eta_sq_results)
```
## Agent bias
```{r}
# Obtain estimated marginal means for the three-way interaction
emm <- emmeans(Decisions, ~ Experiment * Session * Strategy)
emm
```

### Number of decisions
```{r}
AgentBias <- read.csv("/Volumes/TwoTeras/Graph_Stuff/CSVs/visits_counts_extended.csv", sep =",")
# Exclude two participants because they were exposed to Vincent's experiment
Mask_IDs <- AgentBias$ParticipantId %in% c(5238, 8695)
AgentBias <- AgentBias[!Mask_IDs, ]
unique(AgentBias$ParticipantId)
head(AgentBias)
```
```{r}
# Convert Experiment to factor
AgentBias$ExperimentGroup <- as.factor(AgentBias$ExperimentGroup)
AgentBias$Session <- factor(AgentBias$Session,  levels = c("1", "2", "3", "4", "5"))

# Apply effect coding: -0.5 and 0.5
contrasts(AgentBias$ExperimentGroup) <- matrix(c(-0.5, 0.5), ncol = 1)
contrasts(AgentBias$Session) <- contr.treatment(5, base = 1)

# Fit a linear mixed-effects model with interaction terms
visit_model <- lmer(Total ~ Session * ExperimentGroup + (1 | ParticipantId), data = AgentBias)

# Compute R-squared values (marginal and conditional)
r2_values <- r.squaredGLMM(visit_model)
print(r2_values)  # R²m (fixed effects), R²c (fixed + random effects)

# Perform Type II ANOVA to get effect sizes
anova_results <- Anova(visit_model, type = "II")
print(anova_results)

# Compute eta-squared (η²) for fixed effects
eta_sq_results <- eta_squared(visit_model, partial = TRUE)
print(eta_sq_results)
summary(visit_model)
```
```{r}
AgentBiasLikelihood <- read.csv("/Volumes/TwoTeras/Graph_Stuff/CSVs/Probabilities_per_Participant.csv", sep =",")

# Exclude two participants because they were exposed to Vincent's experiment
Mask_IDs <- AgentBiasLikelihood$ParticipantId %in% c(5238, 8695)
AgentBiasLikelihood <- AgentBiasLikelihood[!Mask_IDs, ]

AgentBiasLikelihood <- AgentBiasLikelihood[complete.cases(AgentBiasLikelihood), ]



# Group by ParticipantId, Strategy, and Session, and summarize
df_grouped <- AgentBiasLikelihood %>%
  group_by(Experiment, Strategy, Session) %>%
  summarize(mean_value = mean(Value, na.rm = TRUE))

df_grouped

# Save the data frame to a specified directory and file name
write.csv(df_grouped, file = "/Volumes/TwoTeras/Graph_Stuff/CSVs/Probabilities_per_Participant_grouped.csv", row.names = FALSE)

head(df_grouped)
```
```{r}
# Filter the data to keep only complete cases
df_grouped$ExperimentGroup <- as.factor(df_grouped$Experiment)

# Apply effect coding: -0.5 and 0.5
contrasts(df_grouped$ExperimentGroup) <- matrix(c(-0.5, 0.5), ncol = 1)
```

```{r}
# Fit the linear mixed-effects model with random interce
lmm_model <- lmer(mean_value ~  Strategy * Experiment * Session + (1 | ParticipantId), data = df_grouped)

# Summary of the model
summary(lmm_model)
```
```{r}
AgentBiasGroup <- read.csv("/Volumes/TwoTeras/Resources/Likelihoods.csv")
```

```{r}
# Filter the data to keep only complete cases
AgentBiasGroup$ExperimentGroup <- as.factor(AgentBiasGroup$Experiment)
AgentBiasGroup$Strategy <- as.factor(AgentBiasGroup$Strategy)

# Convert Session to a factor
AgentBiasGroup$Session <- factor(AgentBiasGroup$Session)

# Set contrasts such that sessions 2 to 5 are compared against session 1
contrasts(AgentBiasGroup$Session) <- contr.treatment(levels(AgentBiasGroup$Session), base = 1)

# Apply effect coding: -0.5 and 0.5
contrasts(AgentBiasGroup$ExperimentGroup) <- matrix(c(-0.5, 0.5), ncol = 1)
contrasts(AgentBiasGroup$Strategy) <- matrix(c(-0.5, 0.5), ncol = 1) 
```

```{r}
# Assuming AgentBiasGroup is your data frame and Value is the column of interest
ggplot(AgentBiasGroup, aes(x = Value)) +
  geom_histogram(aes(y = ..density..),  fill = "blue", color = "black") +
  stat_function(fun = dnorm, 
                args = list(mean = mean(AgentBiasGroup$Value), sd = sd(AgentBiasGroup$Value)), 
                color = "red", size = 1) +
  labs(title = "Histogram of Value by Experiment", x = "Value", y = "Density") +
  facet_wrap(~ Experiment) +
  theme_minimal()

```


```{r}
# Model with random intercepts for Row
model_row <- lmer(Value ~ Experiment * Session * Strategy + (1 | Row), data = AgentBiasGroup)

# Summarize the model
summary(model_row)

# Model with random intercepts for Column
model_column <- lmer(Value ~ Experiment * Session * Strategy + (1 | Column), data = AgentBiasGroup)

# Summarize the model
summary(model_column)

```
```{r}
# Compare models using AIC and BIC
AIC(model_row, model_column)
BIC(model_row, model_column)

# Compare models using ANOVA
anova(model_row, model_column)

```
```{r}
# Obtain estimated marginal means for the three-way interaction
emm <- emmeans(model_row, ~ Experiment * Session * Strategy)

# Summary of estimated marginal means
summary(emm)

# Pairwise comparisons
pairs(emm, by = c("Experiment", "Session"))
```

