---
title: "Rancloud_Plot_Gaze_Count"
author: "Tracy Sánchez"
date: "Última actualización: `r format(Sys.Date(), format = '%d %B %Y')`" 
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
    toc_depth: 6
    mathjax: null
    css: doc.css # To set style to maximum in a separate file
---

```{r setup, include=FALSE}
if (!require(remotes)) {
    install.packages("remotes")
}
remotes::install_github('jorvlan/raincloudplots')
library(raincloudplots)

w_package = 3
h_package = 6

# Load required packages
library_packages <- c(
  "dplyr", "tidyr", "corrplot", "ggplot2", "ggrain", "ggpol"
)
lapply(library_packages, library, character.only = TRUE)
```

```{r}
df_2x2 <-read.csv("/Volumes/TwoTeras/0_Experiment_1/Eye_Tracking/Pre_processed/Data_Sets/Complete_Data_AngularV_NO_Outliers.cvs")
```


```{r cars}
df_2x2_spread <- data_2x2(
  array_1 = iris$Sepal.Length[1:50],
  array_2 = iris$Sepal.Length[51:100],
  array_3 = iris$Sepal.Length[101:150],
  array_4 = iris$Sepal.Length[81:130],
  labels = (c('congruent','incongruent')),
  jit_distance = .09,
  jit_seed = 321,
  spread_x_ticks = TRUE) 
```
```{r}
raincloud_2x2_spread <- raincloud_2x2_repmes(
  data = df_2x2_spread,
  colors = (c('dodgerblue', 'darkorange', 'dodgerblue', 'darkorange')),
  fills = (c('dodgerblue', 'darkorange', 'dodgerblue', 'darkorange')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .6,
  spread_x_ticks = TRUE) +

scale_x_continuous(breaks=c(1,2,3,4), labels=c("Pre", "Post", "Pre", "Post"), limits=c(0, 5)) +
  xlab("Time") + 
  ylab("Score") +
  theme_classic()
raincloud_2x2_spread
```
```{r}
raincloud_2x2_spread <- raincloud_2x2_repmes(
  data = df_2x2_spread,
  colors = (c('dodgerblue', 'darkorange', 'dodgerblue', 'darkorange')),
  fills = (c('dodgerblue', 'darkorange', 'dodgerblue', 'darkorange')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .6,
  spread_x_ticks = TRUE) +

scale_x_continuous(breaks=c(1,2,3,4), labels=c("Pre", "Post", "Pre", "Post"), limits=c(0, 5)) +
  xlab("Time") + 
  ylab("Score") +
  theme_classic()
raincloud_2x2_spread
```


```{r}
df_1x1 <- data_1x1(
  array_1 = iris$Sepal.Length[1:50],
  array_2 = iris$Sepal.Length[51:100],
  jit_distance = .09,
  jit_seed = 321)
df_1x1
```
```{r}
#Summarizing to get one per session
Agent_Sessions <- df_2x2 %>%
  group_by(SubjectID, Session) %>%
  summarize( y_axis = sum(Face_Hits %in% c("Body", "Face")))


# The function also need a column to be named jitter, x_axisand y axis
Agent_Sessions <- Agent_Sessions%>%
  rename(id = SubjectID,
         x_axis = Session,
         ) %>%
  mutate(jit = jitter(x_axis, amount = 0.1)
  )
write.csv(Agent_Sessions, "/Users/tracysanchezpacheco/Desktop/Agent_Sessions.csv")
```


```{r}

#Summarizing to get only one number per person ()
Face_Body <- df_2x2 %>%
  group_by(SubjectID) %>%
  summarize(
    Body_Hits = sum(Face_Hits == "Body"),
    Face_Hits = sum(Face_Hits == "Face")
  )
# Long format the summary, Rainclud function requires it 
long_format <- Face_Body %>%
  pivot_longer(
    cols = c(Body_Hits, Face_Hits),
    names_to = "Type",
    values_to = "y_axis"
  )

# The function also need a column to be named jitter, x_axisand y axis

long_format <- long_format %>%
  rename(id = SubjectID) %>%
  mutate(
    x_axis = if_else(Type == "Face_Hits", 1, 2),
    jit = jitter(x_axis, amount = 0.1)
  )
```

```{r}
raincloud_2 <- raincloud_1x1_repmes(
  data = long_format,
  colors = (c('dodgerblue', 'darkorange')),
  fills = (c('dodgerblue', 'darkorange')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .6,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Face", "Body"), limits=c(0, 3)) +
  xlab("Gaze Collider Type") + 
  ylab("Number of Gazes") +
  theme_classic()
raincloud_2
```
```{r}
#Summarizing to get one per session
Agent_Sessions_FB <- df_2x2 %>%
  group_by(SubjectID, Session) %>%
  summarize(
    Body_Hits = sum(Face_Hits == "Body"),
    Face_Hits = sum(Face_Hits == "Face")
  )

# Long format the summary, Rainclud function requires it 
long_format_FB <- Agent_Sessions_FB %>%
  pivot_longer(
    cols = c(Body_Hits, Face_Hits),
    names_to = "Type",
    values_to = "y_axis"
  )

# The function also need a column to be named jitter, x_axisand y axis
long_format_FB <- long_format_FB%>%
  rename(id = SubjectID,
         x_axis = Session,
         ) %>%
  mutate(jit = jitter(x_axis, amount = 0.1)
  )
```

```{r}
# Calculate Pearson correlation
correlation_result <- cor(Face_Body$Body_Hits, Face_Body$Face_Hits)

# Print the result
print(correlation_result)

scale_x_continuous(breaks=c(1,2,3,4,5), labels=c("One", "Two", "Three", "Four", "Five"), limits=c(0, 3)) 
```




```{r}
ggplot(Agent_Sessions, aes(x_axis, y_axis, color=x_axis)) +
  geom_rain(alpha = .5,  id.long.var = "id",  rain.side = "r",
            boxplot.args = list(outlier.shape = NA, alpha = .8),
            violin.args = list(alpha = .8, color = NA),
            boxplot.args.pos = list(width = .1,
            position = ggpp::position_dodgenudge(x = c(1,2,3,4,5))),
            violin.args.pos = list(width = .7,
             position = position_nudge(x = c(rep(-.2, 256*2), rep(-.2, 256*2),# t1
                                             rep(-.2, 256*2), rep(.2, 256*2), # t2
                                             rep(.2, 256*2), rep(.2, 256*2),
                                             rep(-.2, 256*2), rep(-.2, 256*2),
                                             rep(-.2, 256*2), rep(-.2, 256*2)))))+
  theme_classic() +
  guides(fill = 'none', color = 'none')
```
```{r}
ggplot(iris.long[iris.long$time %in% c('t1', 't2'),], aes(time, Sepal.Width, fill = Species, color = Species)) +
  geom_rain(alpha = .5, rain.side = 'f2x2', id.long.var = "id",
            violin.args = list(color = NA, alpha = .7)) +
  theme_classic() +
  scale_fill_manual(values=c("dodgerblue", "darkorange")) +
  scale_color_manual(values=c("dodgerblue", "darkorange")) +
  guides(fill = 'none', color = 'none')
#> Warning: Duplicated aesthetics after name
#> standardisation: alpha
```



```{r}
library(ggplot2)

# Custom function to create a half violin plot
half_violin <- function(...) {
  ggplot2::geom_violin(trim = FALSE, ...) +
    ggplot2::coord_flip() +
    ggplot2::scale_x_reverse()
}


# Your ggplot code
ggplot(long_format_FB, aes(x = x_axis, y = y_axis, fill = Type, color = Type)) +
  geom_violin(trim = TRUE, scale = "area") +
  geom_point(position = position_jitter(width = 0.15), size = 1, alpha = 0.8) +
  geom_boxplot(width = 0.1, position = position_nudge(x = 0.2), outlier.shape = NA, alpha = 0.5) +
  theme_classic()
```
```{r}
library(ggplot2)

ggplot(long_format_FB, aes(x = x_axis, y = y_axis, fill = Type, color = Type)) +
  geom_violin(trim = TRUE, position = position_dodge(0.8)) +
  geom_jitter(width = 0.25, height = 0) +
  geom_boxplot(width = 0.1, outlier.shape = NA, position = position_dodge(0.8)) +
  theme_classic() +
  guides(fill = 'none', color = 'none')
```
```{r}
# Assuming long_format_FB is your data frame
# Sorting the data by id and Type
long_format_FB_sorted <- long_format_FB %>% 
  arrange(id, Type)

# Updated ggplot
ggplot(long_format_FB_sorted, aes(x = x_axis, y = y_axis, group = id, color = Type)) +
  geom_violin(trim = TRUE, position = position_dodge(0.8)) +
  geom_jitter(width = 0.25, height = 0) +
  geom_boxplot(width = 0.1, outlier.shape = NA, position = position_dodge(0.8)) +
  geom_line() +  # This line connects points with the same ID
  theme_classic() +
  guides(fill = 'none', color = 'none')
```



```{r}
ggplot(Agent_Sessions, aes(x_axis, y_axis, fill = Type)) +
  geom_rain(alpha = .5, rain.side = 'f', id.long.var = "id", 
            boxplot.args = list(outlier.shape = NA, alpha = .8),
            violin.args = list(alpha = .8, color = NA),
            boxplot.args.pos = list(width = .1,
             position = ggpp::position_dodgenudge(x = c(-.13, -.13, # t1 old, t1 young
                                                        -.13, .13, 
                                                         .13, .13))),
            violin.args.pos = list(width = .7,
             position = position_nudge(x = c(rep(-.2, 256*2), rep(-.2, 256*2),# t1
                                             rep(-.2, 256*2), rep(.2, 256*2), # t2
                                             rep(.2, 256*2), rep(.2, 256*2))))) +
  theme_classic() +
  scale_fill_manual(values=c("dodgerblue", "darkorange")) +
  scale_color_viridis_c(option =  "A", direction = -1) +
  guides(fill = 'none', color = 'none')
#> Warning: Duplicated aesthetics after name
#> standardisation: alpha
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
