---
title: "Context Questionnaire Exploratory factor analysis"
author: "Tracy Sánchez"
date: "Última actualización: `r format(Sys.Date(), format = '%d %B %Y')`" 
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(psych)
#Read data
ContextQuest <- read.csv("/Users/tracysanchezpacheco/Documents/Resources/ContextQuest.csv", sep =",")
head(ContextQuest)
```
```{r}
library(readr)
library(psych)
#Read data
ContextQuest <- read.csv("/Users/tracysanchezpacheco/Documents/Resources/ContextQuest.csv", sep =",")
head(ContextQuest)
```

## Get the data set in shape
```{r}
#Read data
ContextQuestEFA <- ContextQuest[,(4:7)]
rownames(ContextQuestEFA) <- ContextQuest$ID
head(ContextQuestEFA)

```
## Search for evidence of number of factors 
```{r }
bfi_EFA_cor <- cor(ContextQuestEFA, use='pairwise.complete.obs')
# Scree plot
scree(bfi_EFA_cor, factors = F)
```

## Exploratory Factor Analysis

```{r }
EFA_model = fa(ContextQuestEFA, nfactors=2)
# Scree plot
fa.diagram(EFA_model)
```
## Model Loadings
```{r }
EFA_model$loadings
```


