---
title: "Avatar Questionnaire Exploratory factor analysis"
author: "Tracy Sánchez"
date: "Última actualización: `r format(Sys.Date(), format = '%d %B %Y')`" 
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Avatar Questionnaire exploratory factor analysis 
```{r}
library(readr)
library(psych)
#Read data
AvatarQuest <- read.csv("/Users/tracysanchezpacheco/Documents/Resources/AvatarQuestWide.csv", sep =",")
head(AvatarQuest)
```


```{r}
x=1:56
Atractive <-as.list(sprintf("Atractive %d", x))
Realistic <-as.list(sprintf("Realistic %d", x))
Remember <-as.list(sprintf("Remember %d", x))
append <- append(Atractive, Realistic)  
Colnames <- append(append, Remember)
colnames(AvatarQuest) <- Colnames
head(AvatarQuest)
```

# Search for evidence of number of factors 
```{r }
library(nlme)
corObject=cor(AvatarQuest, method = 'pearson', use="pairwise.complete.obs")
```
```{r}
# mat : is a matrix of data
# ... : further arguments to pass to the native R cor.test function
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(AvatarQuest)
head(p.mat[, 1:5])
```





```{r }
corrplot(bfi_EFA_cor, method="color", tl.col="black", tl.srt=45)
```

# Exploratory Factor Analysis
```{r }
EFA_model = fa(AvatarQuest, nfactors=3)
# Scree plot
fa.diagram(EFA_model)
```

```{r }
EFA_model$loadings
```


